---
# Downloading and setting up git repos

- name: Install tools from github and set permissions
  block:
  - name: Create a directory for each tool to be installed
    ansible.builtin.file:
      group: "{{ group }}"
      mode: 0755
      path: "{{ item.path }}/{{ item.dir_name }}"
      state: directory
    loop: "{{ e_git_repos }}"
    loop_control:
      label: "{{ item.dir_name }}"

  - name: Install github tools
    ansible.builtin.git:
      repo: "{{ item.repo }}"
      dest: "{{ item.path }}/{{ item.dir_name }}"
      force: true
    loop: "{{ e_git_repos }}"
    loop_control:
      label: "{{item.repo}}"

  - name: Set new file privileges -- recursive
    ansible.builtin.file:
      owner: "{{ group }}"
      path: "{{ item.path }}/{{ item.dir_name }}"
      mode: 0755
      recurse: yes
    loop: "{{e_git_repos}}"
    loop_control:
      label: "{{item.repo}}"

# Install Package dependencies
- name: Install package dependencies
  block:
    - name: Setup python packages for required git repos 
      ansible.builtin.command: python3 setup.py install
      args:
        chdir: "{{item.path}}"
      loop: "{{python_setup_external}}"
      loop_control:
        label: "{{item.path}}"

    - name: Install pip dependencies for required git repos
      ansible.builtin.command: python3 -m pip install -r requirements.txt
      args:
        chdir: "{{item.path}}"
      loop: "{{pip_install_external}}"
      loop_control:
        label: "{item.path}"